# Generated by Django 5.2.11 on 2026-02-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentID', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=200)),
                ('CreatedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Departments',
            },
        ),
    ]
