# Generated by Django 5.2.11 on 2026-03-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AddField(
            model_name='departments',
            name='Description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
