# Generated by Django 5.2.11 on 2026-02-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('GroupID', models.AutoField(primary_key=True, serialize=False)),
                ('GroupName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('PermissionID', models.AutoField(primary_key=True, serialize=False)),
                ('PermissionCode', models.CharField(max_length=80)),
                ('Description', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=150)),
                ('PasswordHash', models.CharField(max_length=255)),
                ('IsActive', models.BooleanField(default=True)),
                ('CreatedAt', models.DateTimeField(blank=True, null=True)),
                ('LastLoginAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupID', models.ForeignKey(db_column='GroupID', on_delete=django.db.models.deletion.CASCADE, to='accounts.groups')),
                ('UserID', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
            options={
                'db_table': 'UserGroups',
                'unique_together': {('UserID', 'GroupID')},
            },
        ),
        migrations.CreateModel(
            name='GroupPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PermissionID', models.ForeignKey(db_column='PermissionID', on_delete=django.db.models.deletion.CASCADE, to='accounts.permissions')),
                ('UserID', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='accounts.users')),
            ],
            options={
                'db_table': 'GroupPermissions',
                'unique_together': {('UserID', 'PermissionID')},
            },
        ),
    ]
