# Generated by Django 5.2.11 on 2026-02-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('RecordID', models.AutoField(primary_key=True, serialize=False)),
                ('InvoiceNumber', models.IntegerField()),
                ('MessengerName', models.CharField(max_length=200)),
                ('Subject', models.CharField(max_length=300)),
                ('Description', models.TextField()),
                ('DateReceived', models.DateTimeField()),
                ('DateDispatched', models.DateTimeField(blank=True, null=True)),
                ('Returned', models.CharField(blank=True, max_length=30, null=True)),
                ('DateReturned', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(max_length=30)),
                ('IsDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('DeletedAt', models.DateTimeField(blank=True, null=True)),
                ('RestoredAt', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(blank=True, null=True)),
                ('UpdatedAt', models.DateTimeField(blank=True, null=True)),
                ('DeletedByUserID', models.ForeignKey(blank=True, db_column='DeletedByUserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_deleted', to='accounts.users')),
                ('IncomingDepartmentID', models.ForeignKey(db_column='IncomingDepartmentID', on_delete=django.db.models.deletion.PROTECT, related_name='incoming_records', to='organization.departments')),
                ('OutgoingDepartmentID', models.ForeignKey(blank=True, db_column='OutgoingDepartmentID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_records', to='organization.departments')),
                ('RestoredByUserID', models.ForeignKey(blank=True, db_column='RestoredByUserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_restored', to='accounts.users')),
            ],
            options={
                'db_table': 'Records',
            },
        ),
        migrations.CreateModel(
            name='RecordAttachments',
            fields=[
                ('AttachmentID', models.AutoField(primary_key=True, serialize=False)),
                ('FilePath', models.CharField(max_length=500)),
                ('OriginalFileName', models.CharField(max_length=260)),
                ('UploadedAt', models.DateTimeField(blank=True, null=True)),
                ('UploadedByUserID', models.ForeignKey(db_column='UploadedByUserID', on_delete=django.db.models.deletion.PROTECT, to='accounts.users')),
                ('RecordID', models.ForeignKey(db_column='RecordID', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='records.records')),
            ],
            options={
                'db_table': 'RecordAttachments',
            },
        ),
    ]
