# Generated by Django 5.2.11 on 2026-03-16 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_departments_options_departments_description'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalCompanyNames',
            fields=[
                ('ExternalCompanyNameID', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=255, unique=True)),
                ('CreatedAt', models.DateTimeField(blank=True, null=True)),
                ('UpdatedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'External Company Name',
                'verbose_name_plural': 'External Company Names',
                'db_table': 'ExternalCompanyNames',
                'ordering': ['CompanyName'],
            },
        ),
        migrations.AlterModelOptions(
            name='recordattachments',
            options={'verbose_name': 'RecordAttachment', 'verbose_name_plural': 'RecordAttachments'},
        ),
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.AddField(
            model_name='records',
            name='ExternalDocument',
            field=models.CharField(blank=True, default='No', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='IncomingDepartmentID',
            field=models.ForeignKey(blank=True, db_column='IncomingDepartmentID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_records', to='organization.departments'),
        ),
        migrations.AddField(
            model_name='records',
            name='ExternalCompanyName',
            field=models.ForeignKey(blank=True, db_column='ExternalCompanyNameID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='records.externalcompanynames'),
        ),
    ]
