# Generated by Django 5.2.11 on 2026-02-13 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRequests',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('RequestType', models.CharField(max_length=40)),
                ('RequestDetails', models.TextField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=20, null=True)),
                ('ReviewedAt', models.DateTimeField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(blank=True, null=True)),
                ('RequestedByUserID', models.ForeignKey(db_column='RequestedByUserID', on_delete=django.db.models.deletion.PROTECT, related_name='requests_made', to='accounts.users')),
                ('ReviewedByUserID', models.ForeignKey(blank=True, db_column='ReviewedByUserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_reviewed', to='accounts.users')),
                ('TargetRecordID', models.ForeignKey(blank=True, db_column='TargetRecordID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.records')),
            ],
            options={
                'db_table': 'ActionRequests',
            },
        ),
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('AuditLogID', models.AutoField(primary_key=True, serialize=False)),
                ('EventType', models.CharField(max_length=60)),
                ('EventTime', models.DateTimeField(blank=True, null=True)),
                ('Details', models.TextField(blank=True, null=True)),
                ('IsDeleted', models.BooleanField(blank=True, default=False, null=True)),
                ('DeletedAt', models.DateTimeField(blank=True, null=True)),
                ('RestoredAt', models.DateTimeField(blank=True, null=True)),
                ('ActorUserID', models.ForeignKey(blank=True, db_column='ActorUserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_performed', to='accounts.users')),
                ('DeletedByUserID', models.ForeignKey(blank=True, db_column='DeletedByUserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_deleted', to='accounts.users')),
                ('RestoredByUserID', models.ForeignKey(blank=True, db_column='RestoredByUserID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_restored', to='accounts.users')),
                ('TargetRecordID', models.ForeignKey(blank=True, db_column='TargetRecordID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.records')),
                ('TargetRequestID', models.ForeignKey(blank=True, db_column='TargetRequestID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.actionrequests')),
            ],
            options={
                'db_table': 'AuditLogs',
            },
        ),
    ]
